stages:
  train_base:
    cmd: python scripts/train_base.py --batch_size ${train_base.batch_size} 
      --epochs ${train_base.epochs} --lr ${train_base.lr}
    deps:
    - ai-vs-human-generated-dataset-hw/Train_1
    - ai-vs-human-generated-dataset-hw/Test_1
    - scripts/train_base.py
    - data/dataset.py
    params:
    - train_base
    outs:
    - train_base_model/model/base_model.pth
    - train_base_model/base_train_metrics.json
    metrics:
    - train_base_model/base_test_metrics.json:
        cache: false

  finetune:
    cmd: python scripts/finetune.py --base_model_path models/base_model.pth 
      --batch_size ${finetune.batch_size} --epochs ${finetune.epochs} --lr 
      ${finetune.lr}
    deps:
    - train_base_model/model/base_model.pth
    - ai-vs-human-generated-dataset-hw/Train_2
    - ai-vs-human-generated-dataset-hw/Test_2
    - scripts/finetune.py
    params:
    - finetune
    outs:
    - finetune/model/finetuned_model.pth
    - finetune/finetune_train_metrics.json
    metrics:
    - finetune/finetuned_test_metrics.json:
        cache: false

  evaluate_finetuned:
    cmd: python scripts/evaluate.py --model_path models/finetuned_model.pth 
      --test_csv ai-vs-human-generated-dataset-hw/Test_2/test.csv --test_root ai-vs-human-generated-dataset-hw/Test_2 --output_json 
      metrics/finetuned_eval_metrics.json
    deps:
    - finetune/model/finetuned_model.pth
    - data/Test_2
    outs:
    - finetune/finetuned_eval_metrics.json
    metrics:
    - finetune/finetuned_eval_metrics.json:
        cache: false

  upload_models:
    cmd: python scripts/upload_to_s3.py --model_path models/base_model.pth 
      --model_name resnet18_v1.pth && python scripts/upload_to_s3.py 
      --model_path models/finetuned_model.pth --model_name 
      resnet18_v2_finetuned.pth
    deps:
    - train_base_model/model/base_model.pth
    - finetune/model/finetuned_model.pth
